<a href="https://colab.research.google.com/github/ishwaryac20-prog/Python_DA_Assignment_Numpy_Pandas/blob/main/Python_DA_Assignment_Numpy_Pandas.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Data Analysis Using NumPy and Pandas 🐍

**Python DA Assignment 1 — NumPy and Pandas**

This notebook contains the complete assignment with a clean task-by-task structure and a few emojis in the headings/subheadings for readability.

## Objectives

🟣 Create and manage datasets using NumPy arrays and Pandas DataFrames.  
🟣 Perform indexing, slicing, filtering, and subset retrieval.  
🟣 Apply aggregation functions such as `groupby()`, `mean()`, `value_counts()`, and `unique()`.  
🟣 Manipulate data by updating values, adding columns, and removing rows/columns.  
🟣 Explore NumPy and Pandas operations for efficient data analysis.

In [1]:
import numpy as np
import pandas as pd

## Data Analysis Using NumPy 🔢

NumPy is a powerful Python library for numerical computing. Its main feature is the `ndarray`, which supports efficient numerical operations, indexing, slicing, and mathematical calculations.

### 1. Create a 1D NumPy Array 🌡️

Create a 1D NumPy array named `temperatures_w1` for Week 1 with the given temperature values.

In [2]:
temperatures_w1 = np.array([22.5, 25.3, 20.8, 23.4, 26.1, 24.8, 21.9])

temperatures_w1

array([22.5, 25.3, 20.8, 23.4, 26.1, 24.8, 21.9])

### 2. Inspection and Properties 🔍

Inspect the shape, data type, and number of elements in the array.

In [3]:
print("Inspection and Properties")
print()
print("Shape          :", temperatures_w1.shape)
print("Data type      :", temperatures_w1.dtype)
print("Num of elements:", temperatures_w1.size)

Inspection and Properties

Shape          : (7,)
Data type      : float64
Num of elements: 7


### 3. Array Operations 🌡️

Convert the Week 1 temperatures from Celsius to Fahrenheit.

**Formula:** `Fahrenheit = (Celsius × 9/5) + 32`

Then find the maximum, minimum, and mean temperatures.

In [4]:
temperatures_f = (temperatures_w1 * 9/5) + 32

print("Temperature in Fahrenheit:", np.round(temperatures_f, 2))

print()
print("Max / Min / Mean")
print()
print("Maximum :", np.max(temperatures_f))
print("Minimum :", np.min(temperatures_f))
print("Mean    :", np.mean(temperatures_f))

Temperature in Fahrenheit: [72.5  77.54 69.44 74.12 78.98 76.64 71.42]

Max / Min / Mean

Maximum : 78.98
Minimum : 69.44
Mean    : 74.37714285714286


### 4. Array Slicing and Indexing ✂️

Extract:
- The first three days
- The weekend (last two days)
- The middle three days

In [5]:
print("Slicing and Indexing (Temperatures)")
print()
print("Temp for the first three days  :", temperatures_f[0:3])
print("Temp for the last two days     :", temperatures_f[-2:])
print("Temp for the middle three days :", temperatures_f[2:5])

Slicing and Indexing (Temperatures)

Temp for the first three days  : [72.5  77.54 69.44]
Temp for the last two days     : [76.64 71.42]
Temp for the middle three days : [69.44 74.12 78.98]


### 5. Create a 2D NumPy Array 🧮

Create a 2D array named `temperatures`, where each row represents a different week.

In [6]:
temperatures = np.array([
    [22.5, 25.3, 20.8, 23.4, 26.1, 24.8, 21.9],
    [19.2, 22.5, 21.3, 24.0, 23.5, 22.8, 20.1]
])

temperatures

array([[22.5, 25.3, 20.8, 23.4, 26.1, 24.8, 21.9],
       [19.2, 22.5, 21.3, 24. , 23.5, 22.8, 20.1]])

### 6. Inspect and Slice the 2D Array 🔍

Inspect the shape, data type, and total number of elements. Then extract the temperatures for each week and the weekend temperatures for both weeks.

In [7]:
print("Inspect and Slice")
print()
print("Temp Shape             :", temperatures.shape)
print("Temp Data type         :", temperatures.dtype)
print("Temp (Num of elements) :", temperatures.size)

week_1 = temperatures[0]
week_2 = temperatures[1]

print()
print("====== Temperature for each week ======")
print("Week 1 :", week_1)
print("Week 2 :", week_2)

print()
print("====== Weekend (Last two days) ======")
print("Weekend 1 :", week_1[-2:])
print("Weekend 2 :", week_2[-2:])

Inspect and Slice

Temp Shape             : (2, 7)
Temp Data type         : float64
Temp (Num of elements) : 14

====== Temperature for each week ======
Week 1 : [22.5 25.3 20.8 23.4 26.1 24.8 21.9]
Week 2 : [19.2 22.5 21.3 24.  23.5 22.8 20.1]

====== Weekend (Last two days) ======
Weekend 1 : [24.8 21.9]
Weekend 2 : [22.8 20.1]


## Pandas Series 🐼

A Pandas Series is a one-dimensional labeled array. It consists of values and index labels, making it useful for structured data analysis.

### 1. Creating Pandas Series 📝

Create a Pandas Series named `marks` with marks 95, 92, 89, 85, 80 and custom indexes `Rank1` to `Rank5`.

In [8]:
marks = pd.Series(
    [95, 92, 89, 85, 80],
    index=['Rank1', 'Rank2', 'Rank3', 'Rank4', 'Rank5']
)

print("Pandas Series")
print()
print(marks)

Pandas Series

Rank1    95
Rank2    92
Rank3    89
Rank4    85
Rank5    80
dtype: int64


### 2. Indexing and Slicing 🔎

Use integer indexing, `loc`, `iloc`, and a Boolean mask to access and filter the Series.

In [9]:
# Integer index position: 1st rank student
print("1st rank mark:", marks.iloc[0])

# loc: top 3 ranks using index labels
print()
print("Top 3 ranks:")
print(marks.loc[['Rank1', 'Rank2', 'Rank3']])

# iloc: 3rd-ranked student
print()
print("3rd rank mark:", marks.iloc[2])

# Boolean mask: marks greater than 90
print()
print("Ranks with marks greater than 90:")
print(marks[marks > 90])

1st rank mark: 95

Top 3 ranks:
Rank1    95
Rank2    92
Rank3    89
dtype: int64

3rd rank mark: 89

Ranks with marks greater than 90:
Rank1    95
Rank2    92
dtype: int64


### 3. Manipulating Series ✏️

Modify the first-rank mark, remove the last-rank entry, and compute CGPA by dividing each mark by 10.

In [10]:
# Modify the mark of Rank1 to 100
marks['Rank1'] = 100

# Remove the last rank
marks = marks.drop('Rank5')

# Compute CGPA
CGPA = marks / 10

print("Marks:")
print(marks)

print()
print("CGPA:")
print(CGPA)

Marks:
Rank1    100
Rank2     92
Rank3     89
Rank4     85
dtype: int64

CGPA:
Rank1    10.0
Rank2     9.2
Rank3     8.9
Rank4     8.5
dtype: float64


## Pandas DataFrame 📊

A Pandas DataFrame is a two-dimensional labeled data structure with rows and columns, similar to an Excel spreadsheet or SQL table.

### 1. Creating Pandas DataFrame 🛒

Create a DataFrame named `transactions` using the TransactionID, ProductCategory, Region, and Amount values provided in the assignment.

In [11]:
transactions = pd.DataFrame({
    "TransactionID": [101, 102, 103, 104, 105, 106, 107, 108, 109, 110],
    "ProductCategory": [
        "Electronics", "Clothing", "Electronics", "Furniture", "Clothing",
        "Electronics", "Furniture", "Clothing", "Furniture", "Electronics"
    ],
    "Region": [
        "North", "South", "North", "East", "West",
        "North", "East", "West", "South", "North"
    ],
    "Amount": [200, 150, 300, 450, 200, 250, 300, 180, 350, 400]
})

transactions

,TransactionID,ProductCategory,Region,Amount
0,101,Electronics,North,200
1,102,Clothing,South,150
2,103,Electronics,North,300
3,104,Furniture,East,450
4,105,Clothing,West,200
5,106,Electronics,North,250
6,107,Furniture,East,300
7,108,Clothing,West,180
8,109,Furniture,South,350
9,110,Electronics,North,400


### 2. Data Exploration 🔍

Perform the following:
- Display the DataFrame using `head()` and `tail()`
- Check shape, column names, and data types
- Display `ProductCategory` and `Amount`
- Retrieve the last three columns
- Filter North-region transactions with Amount greater than 200
- Find product category value counts
- Find unique regions
- Find mean Amount by Region

In [12]:
print("First 5 rows:")
display(transactions.head())

print("Last 5 rows:")
display(transactions.tail())

print("Shape:", transactions.shape)
print("Column names:", list(transactions.columns))

print()
print("Data types:")
print(transactions.dtypes)

First 5 rows:


,TransactionID,ProductCategory,Region,Amount
0,101,Electronics,North,200
1,102,Clothing,South,150
2,103,Electronics,North,300
3,104,Furniture,East,450
4,105,Clothing,West,200


Last 5 rows:


,TransactionID,ProductCategory,Region,Amount
5,106,Electronics,North,250
6,107,Furniture,East,300
7,108,Clothing,West,180
8,109,Furniture,South,350
9,110,Electronics,North,400


Shape: (10, 4)
Column names: ['TransactionID', 'ProductCategory', 'Region', 'Amount']

Data types:
TransactionID       int64
ProductCategory    object
Region             object
Amount              int64
dtype: object


In [13]:
# Display ProductCategory and Amount
print("ProductCategory and Amount:")
display(transactions[['ProductCategory', 'Amount']])

# Retrieve the last 3 columns
print("Last 3 columns:")
display(transactions.iloc[:, -3:])

# Filter North region and Amount > 200
filter_df = transactions[
    (transactions['Region'] == 'North') &
    (transactions['Amount'] > 200)
]

print("North region with Amount greater than 200:")
display(filter_df)

# Value counts
print("Product Category Value Counts:")
print(transactions['ProductCategory'].value_counts())

# Unique regions
print()
print("Unique Regions:")
print(transactions['Region'].unique())

# Mean amount by region
print()
print("Mean Amount by Region:")
print(transactions.groupby('Region')['Amount'].mean())

ProductCategory and Amount:


,ProductCategory,Amount
0,Electronics,200
1,Clothing,150
2,Electronics,300
3,Furniture,450
4,Clothing,200
5,Electronics,250
6,Furniture,300
7,Clothing,180
8,Furniture,350
9,Electronics,400


Last 3 columns:


,ProductCategory,Region,Amount
0,Electronics,North,200
1,Clothing,South,150
2,Electronics,North,300
3,Furniture,East,450
4,Clothing,West,200
5,Electronics,North,250
6,Furniture,East,300
7,Clothing,West,180
8,Furniture,South,350
9,Electronics,North,400


North region with Amount greater than 200:


,TransactionID,ProductCategory,Region,Amount
2,103,Electronics,North,300
5,106,Electronics,North,250
9,110,Electronics,North,400


Product Category Value Counts:
ProductCategory
Electronics    4
Clothing       3
Furniture      3
Name: count, dtype: int64

Unique Regions:
['North' 'South' 'East' 'West']

Mean Amount by Region:
Region
East     375.0
North    287.5
South    250.0
West     190.0
Name: Amount, dtype: float64


### 3. Manipulating the DataFrame ✏️

Modify the Amount for TransactionID 102, add a Discount column, remove TransactionID 109, and finally delete the Discount column.

In [15]:
# 1. Modify Amount for TransactionID 102 to 165
transactions.loc[transactions['TransactionID'] == 102, 'Amount'] = 165

print("After modifying TransactionID 102:")
display(transactions)

# 2. Add Discount column (10% of Amount)
transactions['Discount'] = transactions['Amount'] * 0.10

print("After adding Discount:")
display(transactions)

# 3. Remove TransactionID 109
transactions = transactions[transactions['TransactionID'] != 109]

print("After removing TransactionID 109:")
display(transactions)

# 4. Delete Discount column
transactions = transactions.drop(columns=['Discount'])

print("Final DataFrame:")
display(transactions)

After modifying TransactionID 102:


,TransactionID,ProductCategory,Region,Amount
0,101,Electronics,North,200
1,102,Clothing,South,165
2,103,Electronics,North,300
3,104,Furniture,East,450
4,105,Clothing,West,200
5,106,Electronics,North,250
6,107,Furniture,East,300
7,108,Clothing,West,180
9,110,Electronics,North,400


After adding Discount:


,TransactionID,ProductCategory,Region,Amount,Discount
0,101,Electronics,North,200,20.0
1,102,Clothing,South,165,16.5
2,103,Electronics,North,300,30.0
3,104,Furniture,East,450,45.0
4,105,Clothing,West,200,20.0
5,106,Electronics,North,250,25.0
6,107,Furniture,East,300,30.0
7,108,Clothing,West,180,18.0
9,110,Electronics,North,400,40.0


After removing TransactionID 109:


,TransactionID,ProductCategory,Region,Amount,Discount
0,101,Electronics,North,200,20.0
1,102,Clothing,South,165,16.5
2,103,Electronics,North,300,30.0
3,104,Furniture,East,450,45.0
4,105,Clothing,West,200,20.0
5,106,Electronics,North,250,25.0
6,107,Furniture,East,300,30.0
7,108,Clothing,West,180,18.0
9,110,Electronics,North,400,40.0


Final DataFrame:


,TransactionID,ProductCategory,Region,Amount
0,101,Electronics,North,200
1,102,Clothing,South,165
2,103,Electronics,North,300
3,104,Furniture,East,450
4,105,Clothing,West,200
5,106,Electronics,North,250
6,107,Furniture,East,300
7,108,Clothing,West,180
9,110,Electronics,North,400


## Final Summary 🎯

- NumPy 1D and 2D arrays were created and inspected.
- Celsius temperatures were converted to Fahrenheit.
- Maximum, minimum, and mean temperatures were calculated.
- NumPy indexing and slicing were demonstrated.
- Pandas Series indexing, filtering, updating, deleting, and CGPA calculation were completed.
- Pandas DataFrame exploration, filtering, counting, unique-value analysis, and grouping were performed.
- DataFrame values, rows, and columns were manipulated as required.